pom.xml

Connect to H2 database

---

pom.xml
src/main/resources/application.properties

added dependency spring-data-jpa
added application.properties with main fields to connect DB

spring data jpa

---

.gitignore
checkstyle_config.xml
pom.xml
src/main/java/com/text_messenger/controller/UserController.java
src/main/java/com/text_messenger/model/User.java
src/main/java/com/text_messenger/repository/UserRepository.java
src/main/java/com/text_messenger/service/UserService.java
src/main/java/com/textmessenger/App.java
src/main/java/com/textmessenger/controller/UserController.java
src/main/java/com/textmessenger/model/User.java
src/main/java/com/textmessenger/repository/UserRepository.java
src/main/java/com/textmessenger/service/UserService.java

Добавил интеграцию checkstyle, переименовал пакет com.text_messenger -> com.textmessenger так как ругался checkstyle, отступы 2 пробела

Add checkstyle integration

---

src/main/java/com/textmessenger/repository/MessageRepository.java
src/main/java/com/textmessenger/service/MessageService.java

fix file extension and rules and add import message class

---

src/main/java/com/textmessenger/model/Message.java
src/main/java/com/textmessenger/model/Post.java
src/main/java/com/textmessenger/model/User.java
src/main/java/com/textmessenger/repository/PostRepository.java

fixed Post Message temporary switch to long , fix PostRepository

---

src/main/java/com/textmessenger/model/Message.java
src/main/java/com/textmessenger/model/Post.java

fixes entities for clarifies sql

fixed entities for sql

---

src/main/java/com/textmessenger/controller/DialogController.java
src/main/java/com/textmessenger/service/DialogService.java
src/main/java/com/textmessenger/service/DialogServiceImpl.java

Created basic Dialog service and controller classes with crud operation.

created Service and Controller with crud for Dialog

---

REST.MD
src/main/java/com/textmessenger/controller/PostController.java
src/main/java/com/textmessenger/model/User.java
src/main/java/com/textmessenger/service/PostService.java
src/main/java/com/textmessenger/service/PostServiceImpl.java

postService

---

client/src/components/LogIn.js
src/main/java/com/textmessenger/model/entity/User.java
src/main/resources/application.yml

fix mistake with DB name
fix mistake with input type in log in

fix mistake with fields name

---

pom.xml

Test integration

---

pom.xml

remove fail safe it depends in spring boot tests

fix no needed failsafe plug

---

client/src/actions/postsActions.js
client/src/actions/types.js
client/src/actions/userActions.js
client/src/components/Feed.js
client/src/components/LogIn.js
client/src/reducers/index.js
client/src/reducers/posts.js
client/src/reducers/user.js
src/main/java/com/textmessenger/HealthCheckController.java
src/main/java/com/textmessenger/controller/DialogController.java
src/main/java/com/textmessenger/controller/PostController.java
src/main/java/com/textmessenger/controller/UserController.java
src/main/java/com/textmessenger/model/entity/Dialog.java
src/main/java/com/textmessenger/model/entity/Post.java
src/main/java/com/textmessenger/model/entity/User.java
src/main/java/com/textmessenger/service/UserService.java
src/main/java/com/textmessenger/service/UserServiceImpl.java

mapped new user to redux

---

client/package.json
client/src/actions/loaderActions.js
client/src/actions/postsActions.js
client/src/actions/types.js
client/src/components/Feed.js
client/src/components/Loader.js
client/src/reducers/index.js
client/src/reducers/loader.js

**Loader:**
Puts fetching prop in Container. 
From state.loader.fetching. 
Renders conditionally.
**in postActions:**
When getPosts() is toggled -> toggleLoader() is toggled as well. After 3 seconds state changes back to fetching: false.

LOADER on time delay

---

client/src/components/Profile.js

Edit Profile

---

client/src/components/Dialog.js
client/src/components/Dialogs/Dialogs.js
client/src/components/Dialogs/Dialogs.scss
client/src/components/Loader/Loader.js
client/src/components/Messages.js

Выводит на экран сообщение при нажатии на диалог
Слева Вы справа все остальные

View messages simple

---

client/src/actions/dialogActions.js
client/src/components/SearchUser.js
src/main/java/com/textmessenger/controller/DialogController.java
src/main/java/com/textmessenger/service/DialogService.java
src/main/java/com/textmessenger/service/DialogServiceImpl.java

Создается диалог между текущим пользователем и пользователем из поиска на нажатие кнопки Add

Create dialog beetwen two users

---

client/src/components/Dialogs/Dialogs.scss
client/src/components/Message.js
client/src/components/MessagesList.js

-used <paper /> component
-classes object for checking user for current.
-flex in messagelist

material ui over message-item:

---

_mac/git.xml
_mac/laf.xml
_mac/path.macros.xml
client/package.json
client/src/actions/loaderActions.js
client/src/actions/postsActions.js
client/src/actions/userActions.js
client/src/components/Post/Post.js
client/src/components/Post/components/Like.js
client/src/components/Post/components/PostFooter.js
client/src/components/SearchUser.js
client/src/components/User/UserHeaderInfo.js
client/src/components/buttons/ButtonPost/ButtonPost.js
client/src/reducers/loader.js
client/src/reducers/searchUser.js
client/src/views/Feed/Feed.js
codestyles/Default.xml
databaseDrivers.xml
databaseSettings.xml
debugger.xml
filetypes.xml
find.xml
ignore.xml
lombok-plugin.xml
src/main/java/com/textmessenger/repository/UserRepository.java
src/main/java/com/textmessenger/service/UserServiceImpl.java
ui.lnf.xml

_ALL MERGED. Corrected by hand  |||  With likes, retweets ||| Feed: more visual design, specific loader_ 
**Please use this branch to introduce comments or corrections**
_otherwise use **new Master** created after this is merged_

ALL MERGED. Corrected by hand  |||  With likes, retweets ||| feed: more visual design, specific loader 

---

client/src/actions/dialogActions.js
client/src/actions/postsActions.js
client/src/actions/serviceAction.js
client/src/actions/userActions.js
client/src/components/SearchUser.js
client/src/containers/App/App.js
client/src/views/Profile/OtherUserProfile.js
src/main/java/com/textmessenger/RuntimeAddToDataBase.java
src/main/java/com/textmessenger/config/SecurityConfiguration.java
src/main/java/com/textmessenger/controller/UserController.java
src/main/java/com/textmessenger/model/entity/dto/SearchValue.java
src/test/java/com/textmessenger/repository/PostRepositoryTest.java

add FetchData

---

client/src/actions/dialogActions.js
src/main/java/com/textmessenger/controller/MessageController.java
src/main/java/com/textmessenger/model/entity/dto/MessageFromFront.java

add in dialog action message to back wrapper {message:msg}
create dto on the back to transform front message to string

Transform message from front

---

src/main/java/com/textmessenger/controller/CommentController.java
src/main/java/com/textmessenger/controller/DialogController.java
src/main/java/com/textmessenger/controller/MessageController.java
src/main/java/com/textmessenger/controller/PostController.java
src/main/java/com/textmessenger/controller/UserController.java
src/main/java/com/textmessenger/service/UserService.java
src/main/java/com/textmessenger/service/UserServiceImpl.java

cleaning endpoints method and extrude method from controller layer to service layer

Endpoint method cleaning

---

src/main/java/com/textmessenger/service/EmailService.java
src/main/java/com/textmessenger/service/EmailServiceImpl.java
src/main/java/com/textmessenger/service/UserServiceImpl.java

remove unused methods
